name: release zip gen

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: zip resources
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: resources

      - name: zip
        shell: bash
        run: |
          mkdir build
          tar -zcf build/fonts.zip fonts
          tar -zcf build/images.zip images
          tar -zcf build/release.zip images fonts

      - name: release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: "build/**"
          name: resources下载
          body: "资源下载，参见`README.md`。\n`resources.zip`包括了`fonts.zip`和`images.zip`。\n你可以只下载`resources.zip`，或单独下载`fonts.zip`和`images.zip`。"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
