name: update_list

on: 
  - push:
      paths:
        - 'fonts/**'
        - 'images/**'
        - 'update_list.py'

  - pull_request:
      paths:
        - 'fonts/**'
        - 'images/**'
        - 'update_list.py'

jobs:
  build:
    name: update resources list
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          python ./update_list.py

      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER }}
          git add .
          git commit -m "auto update resource_list.json" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
